### ISSUE TITLE
重启打印机后打印失败

### ISSUE THREAD

**Issue by SublimeCT** [boneVidy/node-escpos-addon#1]
Hi vidy，非常感谢你编写的这个库， 我现在有一个 `electron` 项目，打印功能用到了这个库，在生产环境中完美支持 `ESC/POS` 打印，但在重启打印机后报错: 

![A15B07C93680C94E80F7001A4E67B0FC.jpg](https://i.loli.net/2019/04/10/5cadc4c2c1173.jpg)

测试使用的 `USB` 打印机

这个 `err = 6` 错误貌似是 **句柄无效**，但当刷新页面后再执行打印就能成功( `electron` 中的刷新页面会重新创建这个渲染进程，这个模块在渲染进程中引入 ), 也就是当打印失败后退出并重新创建进程并引入这个模块就可以打印成功，我的理解是我需要重新引入这个模块才能打印

此外获取打印机列表是可以正常使用的

可以交个朋友吗？有时间帮我看一下这个问题，感谢

**Comment by boneVidy** [comment]
@SublimeCT 不建议在 rendererProcess直接 使用这个模块，
建议 如果需要在renderProcess直接使用 
建议在 mainProcess 里面require这个模块 然后做 单例，
然后在 rendererProcecss 通过 remote.require方法 导入这个单例

**Comment by boneVidy** [comment]
@SublimeCT 还有 目前并未做usb 的热插拔检测，如果打印机 断开， 需要通过 DIsconnect方法，断开之前的链接。如果要做热插拔检测，可以 在起一个进程，或者work_thread 轮询调用getDeviceList(),然后列表是有新增还是有断开

**Comment by boneVidy** [comment]
@SublimeCT 你现在遇到的这个问题 可以试下这种方法解决
`// usb printer
const iconv = require('iconv-lite');

const escpos =require('node-escpos-addon');
const usblist = escpos.GetUsbDeviceList();
const printer = usblist.find(item => item.service ==='usbprint' || item.deviceName==='USB 打印支持');
const content = iconv.encode("你好啊\n halo cpp!\\n\n\n\n\nn\n\n\n\n", 'GB18030');
const {success, err} = escpos.PrintRaw(printer.path, content);
// 每次调用完毕
escpos.Disconnect(printer.path);
`

**Comment by SublimeCT** [comment]
感谢 @boneVidy , 加入了 `Disconnect()` 方法, 问题已经解决, 这是修改后的代码:

```typescript
    /**
     * 向打印机发送指令
     * @param vid 
     * @param pid 
     * @param command 
     */
    printerDirect(vid: number, pid: number, command: Buffer): Promise<AdapterPrintResult> {
        return new Promise((resolve, reject) => {
            const result = new AdapterPrintResult()
            const device = this.devices.find(d => d.vid === vid && d.pid === pid)
            if (!device) {
                result.message = '[PrinterWinAdapter] device not found, make sure this printer exists!'
                return resolve(result)
            }
            const printer = this._devices.find(d => d.name === device.name)
            console.warn('DEBIG on windows [printer]:', printer)
            if (!printer) {
                result.message = '[PrinterWinAdapter] interinal error: printer not found.'
                return resolve(result)
            }
            const {success, err} = escpos.PrintRaw(printer.path, command)
            // 每次调用完毕断开之前的连接, [issue](https://github.com/boneVidy/node-escpos-addon/issues/1#issuecomment-482052845)
            escpos.DisConnect(printer.path)
            if (!success) {
                result.errCode = err
                result.message = '[PrinterWinAdapter] ///node-escpos-addon print failed with code: ' + err
                resolve(result)
            } else {
                result.status = AdapterPrinteResultStatus.Success
                setTimeout(() => resolve(result), Adapter.EXEC_DELAY) // 延迟执行
            }
        })
    }
```

目前仍然在渲染进程中调用，在扩展层已经封装为单例，生产环境中会禁止用户刷新页面 😄

**Comment by boneVidy** [comment]
@SublimeCT 建议还是 放在mainProcess 利用process fork出一个单例进程，因为打印机崩溃，卡死无响应也会导致整个进程crash，或者卡顿的，如果 放在 fork 出来的进程中就不会有这个问题。之前 我就遇到过一个状况， 打印机 无纸张的 时候 直接卡死整个进程。所以建议你用 process fork 出一个单例进程专门用来打印。
**mainProcess 生成打印单例Process**
![image](https://user-images.githubusercontent.com/10415170/56008767-e63a8c00-5d0f-11e9-8425-3728c0606dae.png)

c**hildProcess 接受打印指令**
![image](https://user-images.githubusercontent.com/10415170/56008783-f05c8a80-5d0f-11e9-94f1-15f63a310952.png)

**Comment by boneVidy** [comment]
@SublimeCT 在 rendererProcess 里面直接调用 node 模块，是很容易内存泄漏的。
这个模块 是我上一个项目做的，由于我现在一直没有windows 电脑，所以这一段时间 一直处于无维护的状态。这里 我 给你一些 我 上一个项目中遇到的一些问题 的建议。

**Comment by SublimeCT** [comment]
@boneVidy 好的，感谢你的建议；

接下来我要重构热更新功能，会把渲染进程打包为普通浏览器可访问的静态文件，*这时扩展功能就必须放到主进程中了*；

然后打印功能放到 `fork` 的单例进程中，然后在主进程中通过 `mainWindow.webContents.executeJavaScript()` 注入扩展功能的 `SDK`

**Comment by boneVidy** [comment]
> @boneVidy 好的，感谢你的建议；
> 
> 接下来我要重构热更新功能，会把渲染进程打包为普通浏览器可访问的静态文件，_这时扩展功能就必须放到主进程中了_；
> 
> 然后打印功能放到 `fork` 的单例进程中，然后在主进程中通过 `mainWindow.webContents.executeJavaScript()` 注入扩展功能的 `SDK`

@SublimeCT electron 有个 preload 可以预先注入脚本，可以试试看， excuteJavascript 的性能和编码体验都不是很好
![image](https://user-images.githubusercontent.com/10415170/56011133-d07d9480-5d18-11e9-903e-5219c40a552e.png)
[https://electronjs.org/docs/api/browser-window](url)

**Comment by SublimeCT** [comment]
@boneVidy nice! 非常感谢 😃，我去看看 API
