### ISSUE TITLE
Build for Windows on linux

### ISSUE THREAD

**Issue by kybarg** [boneVidy/node-escpos-addon#3]
I want to build it on Linux, but use on Windows

seems like lowercase `Windows.h` can solve this issue

**Comment by boneVidy** [comment]
> I want to build it on Linux, but use on Windows
> 
> seems like lowercase `Windows.h` can solve this issue

Sorry, this library currently only supports windows.
And I haven't done escpos printer related development at the moment.
If you want your escpos printer to be cross platform
I suggest you use another library
[https://github.com/song940/node-escpos](url)
